### ISSUE TITLE
Logo concept

### ISSUE THREAD

**Issue by thecodeah** [MorphiaOrg/morphia-docs#2]
I thought I'd it a try and create a new logo for the project. The idea that came to my mind was an M that dissolves into nothingness. Or you know... *morhps* into nothingness.

I haven't been able to get it to look quite right. Perhaps I'll give it a few more tries later on but this is what I got so far.

**Attempt 1**

![inkscape_8twR4MLHXl](https://user-images.githubusercontent.com/21268739/78247887-f254c600-74eb-11ea-88aa-562eb66e2961.png)

At the moment it looks more like a deformed M than a dissolving one, or maybe i've been looking at it for too long...

**Comment by evanchooly** [comment]
I don't know how I missed this one (notifications for this repo are ... inconsitent) or if you're even still "around."  I've been mulling over a new logo for a while, too, and haven't come up with anything good.  Anyway, I'll close this one but happy to have that discussion.
